import { useState } from "react";
import { Pressable,StyleSheet,Text,TextInput,View } from "react-native";
import Button from "@/components/common/Button";
import ErrorMessage from "@/components/common/ErrorMessage";
import type { CreateShelterInput,Shelter,UpdateShelterInput } from "@/types/shelter";
type Props={mode:"create";onSubmit:(v:CreateShelterInput)=>Promise<void>}|{mode:"update";shelter:Shelter;initialUpdate?:UpdateShelterInput;onSubmit:(v:UpdateShelterInput)=>Promise<void>};
export default function ShelterForm(props:Props){const s=props.mode==="update"?props.shelter:undefined;const initial=props.mode==="update"?props.initialUpdate:undefined;const[name,setName]=useState(s?.name||"");const[location,setLocation]=useState(s?.location||"");const[capacity,setCapacity]=useState(String(s?.capacity||""));const[occupancy,setOccupancy]=useState(String(initial?.occupancy??s?.occupancy??0));const[status,setStatus]=useState<"Open"|"Closed">(initial?.operationalStatus??s?.operationalStatus??"Open");const[remarks,setRemarks]=useState(initial?.remarks??s?.remarks??"");const[error,setError]=useState("");const[saving,setSaving]=useState(false);
async function submit(){setError("");const cap=Number(capacity),occ=Number(occupancy);if(!Number.isInteger(occ)||occ<0){setError("Occupancy must be a non-negative whole number.");return;}if(props.mode==="create"&&(!name.trim()||!location.trim()||!Number.isInteger(cap)||cap<1)){setError("Enter a name, location, and positive whole-number capacity.");return;}if(occ>(props.mode==="update"?props.shelter.capacity:cap)){setError("Occupancy cannot exceed shelter capacity.");return;}setSaving(true);try{if(props.mode==="create")await props.onSubmit({name:name.trim(),location:location.trim(),capacity:cap,occupancy:occ,operationalStatus:status,remarks:remarks.trim()});else await props.onSubmit({occupancy:occ,operationalStatus:status,remarks:remarks.trim()});}catch(e){setError(e instanceof Error?e.message:"Could not save shelter.");}finally{setSaving(false);}}
const spaces=Math.max((props.mode==="update"?props.shelter.capacity:Number(capacity)||0)-(Number(occupancy)||0),0);
return <View style={styles.form}>{props.mode==="create"?<><Field label="Shelter name" value={name} set={setName}/><Field label="Location" value={location} set={setLocation}/><Field label="Capacity" value={capacity} set={setCapacity} numeric/></>:<View style={styles.summary}><Text style={styles.title}>{props.shelter.name}</Text><Text style={styles.hint}>{props.shelter.location} · Capacity {props.shelter.capacity}</Text></View>}<Field label="Current occupancy" value={occupancy} set={setOccupancy} numeric/><Text style={styles.hint}>Available spaces: {spaces}</Text><Text style={styles.label}>Operational status</Text><View style={styles.row}>{(["Open","Closed"] as const).map(v=><Pressable key={v} onPress={()=>setStatus(v)} style={[styles.choice,status===v&&styles.active]}><Text>{v}</Text></Pressable>)}</View><Text style={styles.label}>Remarks (optional)</Text><TextInput value={remarks} onChangeText={setRemarks} multiline maxLength={500} style={[styles.input,styles.multiline]} placeholder="Add an update note"/>{error?<ErrorMessage message={error}/>:null}<Button title={saving?"Saving...":props.mode==="create"?"Register shelter":"Review update"} onPress={()=>void submit()} disabled={saving}/></View>;}
function Field({label,value,set,numeric=false}:{label:string;value:string;set:(v:string)=>void;numeric?:boolean}){return <View><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={set} keyboardType={numeric?"number-pad":"default"} style={styles.input}/></View>;}
const styles=StyleSheet.create({form:{backgroundColor:"#fff",borderColor:"#dce6ea",borderRadius:16,borderWidth:1,gap:14,padding:18},label:{color:"#344b5a",fontSize:13,fontWeight:"700",marginBottom:6},input:{borderColor:"#d1dde3",borderRadius:9,borderWidth:1,color:"#183447",minHeight:46,paddingHorizontal:12,paddingVertical:10},multiline:{minHeight:86,textAlignVertical:"top"},hint:{color:"#71818b",fontSize:12},row:{flexDirection:"row",gap:10},choice:{borderColor:"#d1dde3",borderRadius:9,borderWidth:1,paddingHorizontal:18,paddingVertical:11},active:{backgroundColor:"#e5f1f8",borderColor:"#1877b9"},summary:{backgroundColor:"#f3f7f9",borderRadius:10,padding:14},title:{color:"#183447",fontSize:16,fontWeight:"700"}});
